sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.exclusions=**/test/**/*.*,\
  **/configurations/**/*.*,\
  **/controllers/**/*.*,\
  **/dto/**/*.*,\
  **/exceptions/**/*.*,\
  **/mappers/**/*.*,\
  **/repositories/**/*.*,\
  **/liquibase/*/pojo/*.*

sonar.projectKey=florioux_tier2-proxy
sonar.organization=florioux
sonar.host.url=https://sonarcloud.io
