proxy-options.thread-number=1
teardown-policy.quiet-period=2
teardown-policy.timeout=10
teardown-policy.time-unit=SECONDS

proxy.socks.server.enabled=true
proxy.socks.server.address=0.0.0.0
proxy.socks.server.port=3002
proxy.socks.http-object-aggregator-max-content-length=65536

proxy.http.server.enabled=true
proxy.http.server.address=0.0.0.0
proxy.http.server.port=3001
proxy.http.http-object-aggregator-max-content-length=65536

proxy.certificate.server.enabled=true
proxy.certificate.server.address=0.0.0.0
proxy.certificate.server.port=3000
proxy.certificate.ca.endpoint.method=GET
proxy.certificate.ca.endpoint.path=/cert
proxy.certificate.ca.location=${CERTS_FOLDER}

# Distinguished Name (X.500)
proxy.certificate.ca.x500-name=C=EU, ST=IT, L=Rome, O=Mitm Proxy, OU=Mitm Proxy, CN=Mitm Proxy CA

# Private Key Configuration
proxy.certificate.ca.private-key.algorithm=ECDSA
proxy.certificate.ca.private-key.ec-curve=secp521r1
# SecureRandom is generated at runtime and not configured here

# Signature Algorithm
proxy.certificate.ca.signature-algorithm=SHA256withECDSA

# Certificate Cache
proxy.certificate.ca.cache.size=2000
proxy.certificate.ca.cache.expiration=1
proxy.certificate.ca.cache.time-unit=DAYS

# Certificate Validity
proxy.certificate.ca.validity.amount=6
proxy.certificate.ca.validity.buffer=1000
proxy.certificate.ca.validity.unit=MONTHS
proxy.certificate.ca.validity.max-unit=YEARS

simpl.authentication-provider.baseurl=${SIMPL_AUTHENTICATION_PROVIDER_BASEURL}
simpl.authentication-provider.get-credentials-url=${simpl.authentication-provider.baseurl}/v1/credentials/download
simpl.authentication-provider.get-keypair-url=${simpl.authentication-provider.baseurl}/v1/keypairs
simpl.authentication-provider.get-ephemeral-proof-url=${simpl.authentication-provider.baseurl}/v1/agent/ephemeralProof