apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservices.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/spring-config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "microservices.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}-svc-account
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: check-authentication-provider
          image: "curlimages/curl:8.6.0"
          imagePullPolicy: IfNotPresent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: CHECK_CREDENTIAL_PRESENCE
              value: "{{ ternary "true" "false" .Values.initContainers.checkAuthProvider.checkCredentialPresence.enabled }}"
            - name: AUTH_PROVIDER_URL
              value: "{{ tpl .Values.authenticationProviderUrl . }}/actuator/health"
            - name: CREDENTIAL_CHECK_URL
              value: "{{ tpl .Values.authenticationProviderUrl . }}/tier1/v2/credentials/active"
          command:
            - /bin/sh
            - -c
            - |
              set -e

              echo "Checking if authentication-provider is up at $AUTH_PROVIDER_URL ..."

              until curl -f "$AUTH_PROVIDER_URL" | grep '"status":"UP"'; do
                echo "authentication-provider not ready yet. Retrying in 5s..."
                sleep 5
              done

              echo "authentication-provider is up."

              if [ "$CHECK_CREDENTIAL_PRESENCE" = "true" ]; then
                echo "Checking credential presence..."
                until (
                  http_response_code="$(curl -qs $CREDENTIAL_CHECK_URL -o /dev/null -w "%{response_code}")"
                  echo "Check response code: $http_response_code"
                  [[ "$http_response_code" == "200" ]]
                  ); do
                  echo "Waiting credential installation"
                  echo "Retry credentials installation check..."
                  sleep 10
                done
                echo "Credential is installed."
              else
                echo "Credential presence check disabled."
              fi
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: certificates
              containerPort: {{ .Values.server.certificates.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.server.http.port }}
              protocol: TCP
            - name: socks
              containerPort: {{ .Values.server.socks.port }}
              protocol: TCP
          {{- with .Values.env }}
          env:
            {{- range . }}
            - name: {{ .name }}
              value: {{ tpl .value $ | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
