apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.server.certificates.port }}
      targetPort: certificates
      protocol: TCP
      name: certificates
    - port: {{ .Values.server.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.server.socks.port }}
      targetPort: socks
      protocol: TCP
      name: socks
  selector:
    {{- include "microservices.selectorLabels" . | nindent 4 }}
